[package]
name = "Spellcoder"
version = "0.1.0"
edition = "2021"

[dependencies]
cty = "0.2.2"
libc = "0.2.165"
rand = "0.9.0"
raylib = "5.0.2"
safer-ffi = "0.1.13"
worldgen = "0.5.3"

[build-dependencies]
cc = "1.2.1"
